---
title: "Gene_names"
author: "kdanielmorais"
date: "2023-05-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = FALSE, message = FALSE)
```

```{r echo=F}
library(tidyverse)
library(crosstalk)
```

```{r}
# Load data
gene_table <- readxl::read_excel(path = "data/Tabela Mandar Daniel.xlsx")
# Make shared object
sd <- SharedData$new(gene_table)
```

```{r}
# Selectors
bscols(
  filter_select(
    id = "gene_name",
    label = "Gene Name:",
    sharedData = sd,
    group = ~Gene
  ),
  filter_select(
    id = "protein_name",
    label = "Protein Name:",
    sharedData = sd,
    group = ~Name
  ),
    filter_select(
    id = "Phage",
    label = "Phage Name:",
    sharedData = sd,
    group = ~Phage
  )
)
```

```{r datatable}

sd %>% 
  DT::datatable(
    filter = "top",  # allows filtering on each column
    extensions = c(
      "Buttons",  # add download buttons, etc
      "Scroller"  # for scrolling down the rows rather than pagination
    ),
    rownames = FALSE,  # remove rownames
    style = "bootstrap",
    class = "compact",
    width = "100%",
    fillContainer = T,
    options = list(
      dom = "Blrtip",  # specify content (search box, etc)
      deferRender = TRUE,
      scrollY = 300,
      scroller = F,
      columnDefs = list(
        list(
          visible = FALSE,
          targets = c(2, 3, 5:15),
          width = "20"
        )
      ), 
      buttons = list(
        I("colvis"),  # turn columns on and off
        "csv",  # download as .csv
        "excel"  # download as .xlsx
      )
    ),
    colnames = c(
      "Gene" = "Gene",
      "Protein Name" = "Name",
      "Expression" = "Expression",
      "Fold Change" = "Foldchange",
      "Number" = "Number",
      "P-value" = "Pvalue",
      "P-adjusted" = "Padjusted",
      "Approach" = "Approach",
      "Technique" = "Technique",
      "Host Bacteria" = "Bacteria",
      "Medium" = "Medium",
      "Hours post infection" = "Hours post infection",
      "Phage" = "Phage",
      "Strain" = "Strain",
      "MOI" = "MOI",
      "Study Title" = "PAPER",
      "Year" = "Year",
      "Reference" = "Reference",
      "DOI" = "DOI"
    )
  )
```
